language: java

matrix:
  include:
    - jdk: openjdk8
      env: TARGET=checkstyle
    - jdk: openjdk8
      env: TARGET=pmd
    - jdk: openjdk8
      env: TARGET=cpd
    - jdk: openjdk8
      env: TARGET=test
      services: xvfb
    - jdk: openjdk11
      env: TARGET=test
      services: xvfb
    - os: osx
      osx_image: xcode11
      env: TARGET=test

addons:
  apt:
    packages: clasp
  homebrew:
    packages: clasp

install:
  - ./gradlew assemble

script:
  - ./gradlew $TARGET
  - if [ $TARGET = test ]; then ./ci/run.sh; fi

after_success:
  - if [ $TARGET = test -a $TRAVIS_JDK_VERSION = openjdk8 ]; then ./gradlew coveralls; fi
